import dotenv from 'dotenv';
import mongoose from 'mongoose';
import User from '../models/User.js';
import Paper from '../models/Paper.js';
import Dataset from '../models/Dataset.js';

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/rms';

async function main() {
  await mongoose.connect(MONGO_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  console.log('Connected to MongoDB for seeding');

  try {
    // Create demo user
    const user = new User({
      username: 'sofia.torres',
      email: 'sofia.torres@university.edu',
      password: 'password123',
      role: 'researcher'
    });
    await user.save();
    console.log('Created user:', user._id.toString());

    // Create demo paper
    const paper = new Paper({
      title: 'Un Estudio sobre Inestabilidad Genómica y Sus Implicaciones',
      abstract: 'Estudio de ejemplo que cita el dataset de demo.',
      authors: [user._id],
      createdBy: user._id
    });
    await paper.save();
    console.log('Created paper:', paper._id.toString());

    // Create demo dataset
    const dataset = new Dataset({
      title: 'Datos de Secuenciación Genómica - Proyecto Q',
      description: 'Raw genomic sequence output from the Illumina sequencer for Project Q, batch 2. Validated against control.',
      uploader: user._id,
      tags: ['Genomics', 'Raw Data', 'Project Q'],
      project: 'Project Q',
      versions: [
        {
          version: 'v2.1',
          status: 'Validated',
          file: {
            path: 'demo/genomic_project_q_v2.1.csv.gz',
            size: 1200000000,
            mime: 'text/csv+gzip',
            checksum: 'sha256:deadbeefcafebabefeedface'
          },
          uploader: user._id
        }
      ],
      linkedNotebookEntries: [
        { title: 'Initial Analysis - Run 1', refType: 'NotebookEntry', refId: new mongoose.Types.ObjectId('000000000000000000000204') },
        { title: 'Validation Test - Run 1', refType: 'NotebookEntry', refId: new mongoose.Types.ObjectId('000000000000000000000209') },
        { title: 'Figure 1 Generation', refType: 'NotebookEntry', refId: new mongoose.Types.ObjectId('000000000000000000000215') }
      ],
      lineage: [
        { description: "Generated by 'Data Cleaning Script' from 'Raw Sequence - v2.0'", script: 'data-cleaning.py', createdAt: new Date() }
      ]
    });

    // Add citation pointing to the created paper
    dataset.citedInPapers.push({ title: paper.title, paperId: paper._id, status: 'Published', citedAt: new Date() });

    await dataset.save();
    console.log('Created dataset:', dataset._id.toString());

    console.log('Seeding complete.');
  } catch (err) {
    console.error('Seeding error:', err);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  }
}

main();
